# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default   # use the Default pool
  demands:
    - agent.name -equals myaz

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'   # pick Node.js version your React app needs
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build React app'